name: CI

on:
  release:
    types: [created]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/' 

      - run: npm ci

      - name: Build
        run: npm run build

      - name: Run Test
        run: npm test

      - name: Publish to npm
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
        run: npm publish
